# Generated by Django 3.0.4 on 2020-03-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='order_number',
        ),
    ]
